### ISSUE TITLE
the project file cannot be opened

### ISSUE THREAD

**Issue by DoubleCouponDay** [rich-newman/typescript-html-application-vs2017-template#1] opened 2018-10-07 07:54 UTC
After creating a blank, vs blend project using your poject template addon, the following error is displayed in Microsoft Blend for Visual Studio, version 15.8.6.

![image](https://user-images.githubusercontent.com/7555725/46579705-33912480-ca73-11e8-86c7-5757b4f8f3a2.png)

**Comment by rich-newman** [comment] 2018-12-12 14:57
Did you:
1.  Create the project using Visual Studio and then try to open it in Blend?
or
2.  Somehow create the 'HTML Application with TypeScript' from Blend?

If 1/ then this is expected behavior, although I don't get exactly that error message in testing (I get an 'Unsupported' error).  **Blend doesn't support TypeScript, so a project created with this template can't work in Blend.**  You get the same error with other TypeScript and JavaScript project types.

If 2/ then how did you do that? 
 
Blend is quite unfriendly to extension developers in that it allows templates that can't work to be 'installed'.  However, it's supposed to not load them.  The behavior I'm seeing is that you can install the template, but then the project type 'HTML Application with TypeScript' does NOT appear in the File/New/Project... menu, so you can't even try to create one.

**Comment by rich-newman** [comment] 2019-06-01 09:24
Closing this issue due to insufficient information and age

**Closed as completed by rich-newman** 2019-06-01 09:24 UTC
